# Generated by Django 5.1.1 on 2024-10-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectus',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='contectus',
            name='messages',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contectus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contectus',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
